# Generated by Django 2.0.3 on 2018-04-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('score', models.CharField(max_length=4)),
                ('diretor', models.TextField()),
                ('screenwriter', models.TextField()),
                ('actor', models.TextField()),
                ('website', models.TextField()),
                ('country', models.TextField()),
                ('language', models.TextField()),
                ('types', models.TextField()),
                ('date', models.TextField()),
                ('length', models.TextField()),
                ('name', models.TextField()),
                ('imdb', models.TextField()),
                ('episodes', models.TextField()),
                ('length_episodes', models.TextField()),
                ('search_tag', models.CharField(max_length=5)),
                ('image_id', models.CharField(max_length=7)),
            ],
        ),
    ]
