# Generated by Django 2.0.3 on 2018-05-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='search_tag',
        ),
    ]
