# Generated by Django 2.1 on 2018-06-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='movie_name',
            field=models.TextField(),
        ),
    ]
