# Generated by Django 2.1 on 2018-06-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0005_auto_20180604_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='usermovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('movie_title', models.TextField()),
                ('movie_tag', models.TextField()),
            ],
        ),
    ]
